#!/bin/bash
# USAGE: 
# chmod +x trimtex.sh (do this only once)
# ./trimtex.sh insertfilename.tex

# delete all lines up to the line '\maketitle'
# CHANGE THIS PATTERN TO MATCH THE .tex FILES GENERATED BY RSTUDIO
sed -i.backup '/\\maketitle/,$!d' $1

# delete the '\maketitle' line
sed -i.backup '/\\maketitle/d' $1

# delete the line containing '\end{document}'
sed -i.backup '/\end{document}/,$d' $1

# remove the .backup files created in the process
rm -f *.backup